"""
engine -- standalone execution engine for SQLX ETL projects generated by the
sqlx-etl-generator Claude Code Skill.

Independent of Claude: nothing in this package imports or invokes an LLM,
reads a source document (source_schema.md, target_schema.md, the STTM
workbook, udf.md, folder_hierarchy.md), or reasons about ETL logic. It reads
already-generated metadata and SQLX, and executes SQL. See README.md for the
full architecture.
"""

from engine.database import DatabaseExecutor, MockDatabaseExecutor
from engine.exceptions import (
    DatabaseConnectionError,
    EngineError,
    ExecutionFailure,
    ExecutionPlanError,
    SQLXParseError,
    ValidationError,
)
from engine.executor import Engine, StepOutcome
from engine.logger import ExecutionLogger
from engine.models import (
    ConnectionConfig,
    ExecutionPlan,
    ExecutionRecord,
    ExecutionResult,
    ExecutionStatus,
    ExecutionStep,
    SqlxConfig,
    SqlxFile,
    Stage,
)
from engine.parser import parse_sqlx
from engine.planner import ExecutionPlanner
from engine.postgres import PostgresExecutor, resolve_connection_config

__all__ = [
    "ConnectionConfig",
    "DatabaseConnectionError",
    "DatabaseExecutor",
    "Engine",
    "EngineError",
    "ExecutionFailure",
    "ExecutionLogger",
    "ExecutionPlan",
    "ExecutionPlanError",
    "ExecutionPlanner",
    "ExecutionRecord",
    "ExecutionResult",
    "ExecutionStatus",
    "ExecutionStep",
    "MockDatabaseExecutor",
    "PostgresExecutor",
    "SQLXParseError",
    "SqlxConfig",
    "SqlxFile",
    "Stage",
    "StepOutcome",
    "ValidationError",
    "parse_sqlx",
    "resolve_connection_config",
]
