-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND
-- Run against: intermediate_db
-- UDF bodies copied verbatim from udf.md -- 1 block(s) found.
-- This is a copy, not a re-implementation: the source document is authoritative.

CREATE OR REPLACE FUNCTION fn_full_name(p_first_name text, p_last_name text)
RETURNS text AS $$
    SELECT trim(both ' ' from coalesce(p_first_name, '') || ' ' || coalesce(p_last_name, ''));
$$ LANGUAGE sql IMMUTABLE;
