-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND
-- Run against: intermediate_db
-- Staging tables themselves are created by each table's read.sqlx at run time
-- (CREATE TABLE IF NOT EXISTS), not here -- this script only prepares the namespace.

CREATE SCHEMA IF NOT EXISTS public;
