-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND
-- Bootstrap reset for database: target_db
-- Source: metadata/schema/target_schema.json
--
-- Truncates every table this schema declares, respecting foreign-key dependency order
-- (children before parents) so no FK violation is possible regardless of run order.
-- This script only ever runs when a human executes it manually — see bootstrap/README.md.

TRUNCATE TABLE warehouse.DIM_CUSTOMER CASCADE;
TRUNCATE TABLE warehouse.FACT_ORDER CASCADE;
