-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND (except to fill in TODOs below)
-- Sample data STUB for database: source_db
-- Source: metadata/schema/source_schema.json
--
-- No sample data input was declared for this Generate run (Source Schema, Target Schema,
-- STTM Workbook, User Defined Functions, Folder Hierarchy do not include row-level sample
-- data). Per ADR-001 §5/§9, this generator does NOT fabricate business data — inventing
-- plausible-looking rows would misrepresent synthetic content as real example data.
--
-- Fill in real or synthetic values below, or supply a sample-data input in a future run
-- if this input type is added (see docs/FUTURE_ENHANCEMENTS.md).

-- TODO: populate sample rows for source.CUSTOMER (customer_id, first_name, last_name, status, created_at)
-- INSERT INTO source.CUSTOMER (customer_id, first_name, last_name, status, created_at) VALUES
--     (/* 5 value(s) here */);

-- TODO: populate sample rows for source.CUSTOMER_ORDER (order_id, customer_id, order_date, amount, status)
-- INSERT INTO source.CUSTOMER_ORDER (order_id, customer_id, order_date, amount, status) VALUES
--     (/* 5 value(s) here */);

