-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND
-- Ensures the default working schema exists in each database before DDL runs.

-- source_db: run against that database
CREATE SCHEMA IF NOT EXISTS source;

-- intermediate_db: run against that database
CREATE SCHEMA IF NOT EXISTS staging;

-- target_db: run against that database
CREATE SCHEMA IF NOT EXISTS warehouse;
