-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND
-- postgres_fdw bridge: read source_db from intermediate_db
--
-- Run against:  intermediate_db
-- Foreign schema created: fdw_source_db
--
-- Connection details for source_db are environment-specific and cannot be
-- derived from the input documents -- supply them as psql variables:
--   psql -d intermediate_db \
--     -v remote_host=<host> -v remote_port=5432 \
--     -v remote_user=<user> -v remote_password=<password> \
--     -f 02_create_fdw_intermediate_to_source.sql

CREATE EXTENSION IF NOT EXISTS postgres_fdw;

DROP SERVER IF EXISTS fdw_source_db_srv CASCADE;

CREATE SERVER fdw_source_db_srv
    FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (host :'remote_host', port :'remote_port', dbname 'source_db');

CREATE USER MAPPING FOR CURRENT_USER
    SERVER fdw_source_db_srv
    OPTIONS (user :'remote_user', password :'remote_password');

CREATE SCHEMA IF NOT EXISTS fdw_source_db;

IMPORT FOREIGN SCHEMA public
    LIMIT TO (CUSTOMER, CUSTOMER_ORDER)
    FROM SERVER fdw_source_db_srv
    INTO fdw_source_db;
