-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND
-- postgres_fdw bridge: read intermediate_db from target_db
--
-- Run against:  target_db
-- Foreign schema created: fdw_intermediate_db
--
-- Connection details for intermediate_db are environment-specific and cannot be
-- derived from the input documents -- supply them as psql variables:
--   psql -d target_db \
--     -v remote_host=<host> -v remote_port=5432 \
--     -v remote_user=<user> -v remote_password=<password> \
--     -f 03_create_fdw_target_to_intermediate.sql

CREATE EXTENSION IF NOT EXISTS postgres_fdw;

DROP SERVER IF EXISTS fdw_intermediate_db_srv CASCADE;

CREATE SERVER fdw_intermediate_db_srv
    FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (host :'remote_host', port :'remote_port', dbname 'intermediate_db');

CREATE USER MAPPING FOR CURRENT_USER
    SERVER fdw_intermediate_db_srv
    OPTIONS (user :'remote_user', password :'remote_password');

CREATE SCHEMA IF NOT EXISTS fdw_intermediate_db;

IMPORT FOREIGN SCHEMA public
    LIMIT TO (<staging tables are named per metadata/build/*.buildspec.json:staging_table -- import per-table after Generate runs, e.g. IMPORT FOREIGN SCHEMA public LIMIT TO (stg_...) ...>)
    FROM SERVER fdw_intermediate_db_srv
    INTO fdw_intermediate_db;
