-- Generated by sqlx-etl-generator · DO NOT EDIT BY HAND
-- postgres_fdw bridge: read target_db from intermediate_db
--
-- Run against:  intermediate_db
-- Foreign schema created: fdw_target_db
--
-- Unlike db/01_init/02_create_fdw_intermediate_to_source.sql, this bridge targets
-- tables that do not exist yet at bootstrap time (they are created at pipeline run
-- time by each table's read.sqlx -- see docs/ASSUMPTIONS.md). IMPORT FOREIGN SCHEMA
-- introspects the remote catalog immediately and would fail here; CREATE FOREIGN
-- TABLE does not validate the remote table until it is actually queried, so each
-- foreign table is declared explicitly instead, with the exact column shape already
-- known from metadata/build/*.buildspec.json.
--
-- Connection details for target_db are environment-specific and cannot be
-- derived from the input documents -- supply them as psql variables:
--   psql -d intermediate_db \
--     -v remote_host=<host> -v remote_port=5432 \
--     -v remote_user=<user> -v remote_password=<password> \
--     -f 04_create_fdw_intermediate_to_target.sql

CREATE EXTENSION IF NOT EXISTS postgres_fdw;

DROP SERVER IF EXISTS fdw_target_db_srv CASCADE;

CREATE SERVER fdw_target_db_srv
    FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (host :'remote_host', port :'remote_port', dbname 'target_db');

CREATE USER MAPPING FOR CURRENT_USER
    SERVER fdw_target_db_srv
    OPTIONS (user :'remote_user', password :'remote_password');

CREATE SCHEMA IF NOT EXISTS fdw_target_db;

CREATE FOREIGN TABLE fdw_target_db.dim_customer (
    customer_key integer NOT NULL,
    full_name varchar(200) NOT NULL,
    status varchar(20) NOT NULL
) SERVER fdw_target_db_srv OPTIONS (schema_name 'warehouse', table_name 'dim_customer');

CREATE FOREIGN TABLE fdw_target_db.fact_order (
    order_key integer NOT NULL,
    customer_key integer NOT NULL,
    order_date date NOT NULL,
    amount numeric(12,2) NOT NULL
) SERVER fdw_target_db_srv OPTIONS (schema_name 'warehouse', table_name 'fact_order');

